/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MyPlugin = class extends import_obsidian.Plugin {
  onload() {
    this.addCommand({
      id: "move-mermaidjs-variable-declarations-up",
      name: "Clean code for Mermaid.js ( [ graph | flowchart ] )",
      editorCallback: (editor, view) => {
        var selection_old = editor.getSelection();
        var check_graph_type = ["graph", "flowchart"];
        var top_lines = selection_old.split("\n").filter((d) => {
          if (d !== "")
            return d;
        }).slice(0, 2);
        if (top_lines[0].trim() !== "```mermaid" && !top_lines[1].trim().match(/[graph flowchart]/g))
          return;
        var selection_copy = JSON.parse(JSON.stringify(selection_old));
        console.log(selection_old, selection_copy);
        var re_variables_pattern = /([\w\d\_\/]+[\(\[\>][^\)\]\<]+[\)\]]?[^&\.\n\s][\"\']?[^&\n\-]*[\)\]\<])/g;
        var re_variables = selection_old.match(re_variables_pattern);
        console.log(re_variables);
        var clean_variables = re_variables == null ? void 0 : re_variables.map((d) => {
          var parenthesis_pattern = /[\(\[\>]/g;
          var short_name = d.split(parenthesis_pattern)[0];
          console.log("vars_ " + d + " _ " + short_name);
          selection_copy = selection_copy.replace(d, short_name);
          return "    " + d;
        });
        console.log("# ", selection_copy);
        var vars_formatted = clean_variables == null ? void 0 : clean_variables.join("\n");
        var final_code = selection_copy.split("\n").slice(0, 2).join(" \n") + "\n\n\n%%var space start" + vars_formatted + "\n%%var space end\n\n\n" + selection_copy.split("\n").slice(2).join("\n");
        if (final_code.match(/\%\%var space start/g).length > 1) {
          var temp = final_code.split("%%var space end").splice(0, 1);
          var temp2 = final_code.split("%%var space end").splice(2);
          final_code = temp + "\n%%var space end" + temp2;
        }
        var final_code_ = top_lines.join("\n") + "\n\n%%var space start\n" + final_code.split("%%var space start")[1].replace(top_lines[1], "");
        final_code_ = final_code_.replace("\n\n\n\n\n", "");
        console.log(final_code_);
        console.log(top_lines);
        editor.replaceSelection(final_code_);
      }
    });
    this.addCommand({
      id: "regex-for-mermaid-style",
      name: "Regex for Mermaid.js style ( [ style | class ] )",
      editorCallback: async (editor, view) => {
        var document = this.app.workspace.getActiveFile();
        if (!(document == null ? void 0 : document.name))
          return;
        var document_txt = await this.app.vault.read(document);
        var selection = editor.getSelection().split("\n")[0];
        var style_type = selection.split(" ").slice(0, 1);
        var style_val = selection.split(" ").slice(-1);
        var style_regex = selection.split(" ").slice(1, 2);
        console.log("document text: ", document_txt);
        console.log("selection: ", selection);
        console.log("fields: ", style_type, style_regex, style_val);
        var all_vars_raw = document_txt.match(/([\w\d\_\/]+[\(\[\>][^\)\]\<]+[\)\]]?[^&\.\n\s][\"\']?[^&\n\-]*[\)\]\<])/g);
        var parenthesis_pattern = /[\(\[\>]/g;
        var all_vars_clean = all_vars_raw == null ? void 0 : all_vars_raw.map((d) => d.split(parenthesis_pattern)[0]);
        console.log("all vars: ", all_vars_clean);
        var regex_code = String(style_regex).split(",")[0].replace("/", "").replace("/", "");
        console.log("re", regex_code);
        var custom_regex = new RegExp(String(regex_code), "g");
        var retrieved_vars = all_vars_clean == null ? void 0 : all_vars_clean.filter((d) => {
          if (d.match(custom_regex)) {
            return d;
          }
        });
        console.log("retrieved vars: ", retrieved_vars);
        if (editor.getSelection().split("\n")[0].split(" ")[0] === "style") {
          var retrieved_vars_formatted = retrieved_vars.map((re) => {
            return [style_type, re, style_val].join(" ");
          });
          editor.replaceSelection(retrieved_vars_formatted.join("\n"));
        } else if (editor.getSelection().split("\n")[0].split(" ")[0] === "class") {
          var retrieved_vars_formatted_class = [style_type, retrieved_vars == null ? void 0 : retrieved_vars.join(","), style_val].join(" ");
          editor.replaceSelection(retrieved_vars_formatted_class);
        }
      }
    });
    this.addCommand({
      id: "create-files-from-text",
      name: "Create files from text",
      editorCallback: (editor, view) => {
        var _a, _b;
        const basePath = this.app.vault.adapter.basePath;
        var activeFolder = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.parent.path;
        console.log(activeFolder, (_b = this.app.workspace.getActiveFile()) == null ? void 0 : _b.path);
        var selection = editor.getSelection();
        var file_names = selection.split("\n").filter((d) => {
          if (d !== "") {
            return d.trim();
          }
        });
        var files = this.app.vault.getFiles().map((d) => d.path);
        console.log("old_files ", files);
        file_names.map((d) => {
          if (!files.includes(activeFolder + `/${d}.md`)) {
            this.app.vault.create(activeFolder + `/${d}.md`, "");
          } else {
            console.log("file already exists");
          }
        });
      }
    });
  }
  onunload() {
  }
};
